apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: ticketting
build:
  local:
    push: false
  artifacts:
    - image: naveenkum2r/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
